routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/




// Route for Backend panel
Route::group(['prefix' => 'backend', 'middleware'=>'role:admin|author' ], function(){


    Route::get('/', function () {
        return view('backend.index');
    })->name('dashboard');

    /*
     * Backend Categories Route
     *
     */
       Route::group(['middleware'=>'role:admin' ], function(){
       Route::resource('categories','Backend\BackendCategoryController',['except' => ['index','show']]);
       Route::get('categories/{parent_id?}', 'Backend\BackendCategoryController@index')->name('categories.index');
       Route::get('categories/delete/{category_id}', 'Backend\BackendCategoryController@delete')->name('categories.delete');

       /*
        * Backend User Route
        *
        */

       Route::resource('users','Backend\BackendUserController');
       Route::get('users/delete/{user_id}', 'Backend\BackendUserController@delete')->name('users.delete');

    });


    /*
     * Backend Post Route
     *
     */
    Route::delete('posts/destroyTrashed', 'Backend\BackendPostController@destroyTrashed')->name('posts.destroyTrashed');
    Route::resource('posts','Backend\BackendPostController',['except' => ['show']]);
    Route::get('posts/trash', 'Backend\BackendPostController@trash')->name('posts.trash');
    Route::get('posts/restore/{post}', 'Backend\BackendPostController@restore')->name('posts.restore');



    /*
     * Edit Profile User : Accessible for Admin And Author
     *
     */

    Route::get('profile', 'Backend\BackendUserController@editProfile')->name('user.profile');
    Route::post('profile/{profile}', 'Backend\BackendUserController@updateProfile');



});


Auth::routes();



/*
 * Public Post
 *
 */

Route::get('/', ['uses' => 'Blog\BlogController@index', 'as' => 'blog.index']);
Route::get('/{slug}','Blog\BlogController@showPost')->name('blog.showPost');


/*
 * Public Category
 *
 */
Route::get('/category/{name}','Blog\BlogController@showPostsInCategory')->name('blog.showPostsInCategory');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Post extends Model
{

    use Sluggable;


    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */

    protected $dates = ['published_at','deleted_at','publish_date'];

    protected $fillable = [
                             'title', 'abstract', 'content',
                             'status', 'publish_date',
                             'deleted_by', 'deleted_at',
                             'photo_filename','slug'
    ];


    public $image_path='/images/'; // Where we store images (Relative to Public folder)



    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }



    /**
     * Get the user that wrote the post.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }


    /**
     * Relation with Seo table
     */
    public function seo()
    {
        return $this->morphMany('App\Seo', 'seoble');

    }


    /**
     * Get the user that DELETE the post.
     */
    public function deletedBy()
    {
        return $this->belongsTo('App\User','deleted_by');
    }

    /**
     * The many-to-many relationship between posts and categories.
     *
     * @return BelongsToMany
     */
   public function categories()
    {
        return $this->belongsToMany('App\Category', 'category_post');
    }


    /**
     * Scope for retrieve only not deleted element
     * @param $query
     * @return mixed
     */
    public function scopeActive($query)
    {
        return $query->where('status', '<>', 'deleted');

    }



    /**
     * Scope for retrieve only deleted element
     *
     * @param $query
     * @return mixed
     */
    public function scopeTrashed($query)
    {
        return $query->where('status', 'deleted');
    }



    /**
     * Scope for retrieve only published element
     *
     * @param $query
     * @return mixed
     */
    public function scopePublished($query)
    {
        return $query->where('status', 'publish')->where('publish_date', '<=', Carbon::now());
    }



    public function setPublishDateAttribute($date)
    {
        $this->attributes['publish_date'] = Carbon::createFromFormat('d/m/Y',$date);
    }

    public function getPublishDateAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y');
    }






}

app/Http/Controllers/Backend/BackendCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class BackendCategoryController extends Controller
{



    /**
     * The category repository instance.
     */
    protected $categories;

    /**
     * Assign Category Model in Controller
     *
     * @param  Category $categories
     */
    public function __construct(Category $categories)
    {
        $this->categories = $categories;
    }




    /**
     * Display a listing of all the categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($parent_id=0)
    {


        // Get the categories child of the $id
        $categories = Category::childOf($parent_id)->withCount('children')->paginate(10);

        $next_parent_id = 0;
        $parent_name = null;



        if($parent_id>0){
            $current_parent_category = Category::findOrFail($parent_id);

            // Save the next Parent Category
            $next_parent_id = $current_parent_category->parent_id;
            //Get the current name of the category parent
            $parent_name = $current_parent_category->name;
        }

       return view('backend.categories.index', compact('categories','next_parent_id','parent_name'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories_tree = $this->categories->listTreeCategories();
        if($categories_tree>0) {
            $categories = $this->categories->linearizeCategoryArray($categories_tree);
        }

        return view('backend.categories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // Set some rules, I Set here because are only few rows
        $this->validate( $request, [
            'name' => 'required|max:250',
            'parent_id' => 'required|numeric|min:0',
        ]);

        //Recovery input data
        $input_data = $request->all();

        // Create new category
        $new_category = $this->categories->create($input_data);

        if ($new_category) {
                //  Create new insert in pivot table
                $seo_data = $new_category->seo()->create($input_data);
                $new_category->seo()->save($seo_data);

            \Session::flash('flash_message_success', 'Success! Entry saved.');
        }else{
            \Session::flash('flash_message_error', 'Error! Entry Not saved.');
        }






        // Return to list Category page
        return redirect()->route('categories.index');

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categories->findOrFail($id);

        $categories_tree = $category->listTreeCategories();
        $categories = $category->linearizeCategoryArray($categories_tree);

        // retrieve seo data
        $seo = $category->seo->first();



        return view('backend.categories.edit', compact('category','categories','seo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // Set some rules, I Set here because are only few rows
        $this->validate( $request, [
            'name' => 'required|max:250',
            'parent_id' => 'required|numeric|min:0',
        ]);

        //Recovery input data
        $input_data = $request->all();

        $category = $this->categories->find($id);


        if ($category->update($input_data)) {

            $category->seo()->update(['title_tag'=>$input_data['title_tag'], 'description_tag'=>$input_data['description_tag']]);

            \Session::flash('flash_message_success', 'Success! Entry updated.');
        }else{
            \Session::flash('flash_message_error', 'Error! Entry Not updated.');
        }


        return redirect()->route('categories.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     * We retrieve the user choose about how manage sub folder and posts
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        //Recovery input data
        $input_data = $request->all();

        if(intval($input_data['delete_option'])>0){

            switch ($input_data['delete_option']){

                case 1 : $result = $this->categories->deleteCategoryAndSubcategory($id);
                         break;

                case 2 : $result = $this->categories->moveSubcategory($id,$input_data['move_in_id_category']);
                          break;

                case 3 :  $result = $this->categories->movePostsToCategory($id, $input_data['new_id_category']);

                         break;
            }

        }



        if($result){
            \Session::flash('flash_message_success', 'Success! Category deleted.');
        }else{
            \Session::flash('flash_message_error', 'Error! Category Not deleted.');
        }

        return redirect()->route('categories.index');
    }




    /**
     * Show the form with options for delete the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $category = Category::findOrFail($id);

        //Check some point
        // 1) Did The Category selected has sub-categories?
        // If it has, so I need to ask to user what they want to do with subfolder (delete, Move)
            $has_sub_category = $category->children()->count();

         //2) Did the category selected has post?
        //If it has,  so I need to ask to user what they want to do with Posts (delete, Move)
            $has_posts = $category->posts()->count();

        // Get all Category tree except the category branch and its related sub category
        $categories_tree = $this->categories->listTreeCategories(0,$id);

        // Linearize in array
        $categories_available = $this->categories->linearizeCategoryArray($categories_tree);

        return view( 'backend.categories.delete', compact('category', 'has_sub_category', 'has_posts', 'categories_available') );
    }



}

app/Http/Controllers/Backend/BackendPostController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\PostCreateRequest;
use App\Http\Requests\PostUpdateRequest;
use App\Post;
use App\User;
use App\Repositories\BackendPostRepository;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackendPostController extends Controller
{


    /**
     * The post repository instance.
     */
    protected $postRepository;

    /**
     * Assign Category Model in Controller
     *
     * @param  BackendPostRepository $post
     * @return void
     */
    public function __construct(BackendPostRepository $post)
    {

        $this->postRepository = $post;
    }




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Check the role of the user

        $posts = $this->postRepository->listPosts();

        return view('backend.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $all_categories = $this->postRepository->loadCategories();

        return view('backend.posts.create', compact('all_categories'));
    }

    /**
    /**
     * Save the specified resource and check validation rule in PostCreateRequest.php
     *
     * @param  App\Http\Requests\PostCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostCreateRequest $request)
    {

        $this->postRepository->save($request);

        return redirect('/backend/posts');

    }


    /**
     * Show the form for editing the specified resource.
     * The rules for access are are stored in in app/Policies/Backend/BackendPostPolicy.php
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        // Load all the data for the Post from the repository in app/Repositories/BackendPostRepository.php
        $data = $this->postRepository->load($id);

        // Check the policy for the post, that are stored in app/Policies/Backend/BackendPostPolicy.php
        /*
         *   [
            'post' => // The post Object
            'all_categories' // All the categories
            'category_post' // Id of all the categories set for the post
            'status' => // All status available for the post
             'seo' => // Seo data for the post
        ];
         */

        return view( 'backend.posts.edit', $data );
    }



    /**
     * Update the specified resource and check validation rule in PostUpdateRequest.php
     *
     * @param  App\Http\Requests\PostUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, $id)
    {
        $post = $this->postRepository->find($id);

        if ($this->postRepository->update($request, $id)) {
            \Session::flash('flash_message_success', 'Success!');
        }else{
            \Session::flash('flash_message_error', 'Error!');
        }

        return redirect()->route('posts.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     * The method can be called only via AJAX
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $post = $this->postRepository->find($id);

        $this->authorize('delete', $post);

        // check to see if the request is
        // an AJAX call.
        if ($request->ajax()) {
            $this->postRepository->delete($id);
        }
    }





    /**
     * Display a listing of the post soft-deleted.
     *
     * @return \Illuminate\Http\Response
     */
    public function trash()
    {
        $posts = $this->postRepository->listPosts(true);

        return view('backend.posts.trashed', compact('posts'));
    }


    /**
     *
     *
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {

        // Load all the data for the Post from the repository in app/Repositories/BackendPostRepository.php
        $data = $this->postRepository->loadRestore($id);

        // Check the policy for the post, that are stored in app/Policies/Backend/BackendPostPolicy.php
        /*
         *   [
            'post' => // The post Object
            'all_categories' // All the categories
            'category_post' // Id of all the categories set for the post
            'status' => // All status available for the post
        ];
         */
      return view('backend.posts.edit', $data);
    }




    /**
     * Remove the specified resource earlier trashed ( soft delete ).
     * The method can be called only via AJAX
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroyTrashed(Request $request)
    {
        // check to see if the request is
        // an AJAX call.
        if ($request->ajax()) {
          return  $this->postRepository->deleteTrashed($request['id']);
         }
    }

}

resources/views/backend/posts/create.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header">
        <h1> Post </h1>
    </section>


    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('posts.index') }}" class="btn btn-info"><i class="fa  fa-angle-double-left"></i> Back </a>
        </div>
    </section>



        <section class="content">

        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

            @include('includes.form_error')
            @include('includes.message')


                {{ Form::open(['method'=>'POST', 'action' => 'Backend\BackendPostController@store','files'=>true]) }}
                <div class="row">
                <div class="col-md-8">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Create a new post</h3>
                        </div>


                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#text_tab" data-toggle="tab" aria-expanded="true">Post</a></li>
                                <li class=""><a href="#category_tab" data-toggle="tab" aria-expanded="false">Categories</a></li>
                                <li class=""><a href="#photo_tab" data-toggle="tab" aria-expanded="false">Image</a></li>
                                <li class=""><a href="#seo_tab" data-toggle="tab" aria-expanded="false">Seo</a></li>

                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="text_tab">
                                    <div class="box-body">
                                        <div class="form-group  @if ($errors->has('title')) has-error @endif">
                                            {{ Form::label('title','Title (required) ') }}
                                            {{ Form::text('title',null,['class'=>'form-control','placeholder'=>'Enter the title']) }}
                                            @if ($errors->has('title'))
                                                <small class="help-block">{{ $errors->first('title') }}</small> @endif
                                        </div>

                                        <div class="form-group  @if ($errors->has('abstract')) has-error @endif">
                                            {{ Form::label('abstract','Abstract') }}
                                            {{ Form::textarea('abstract',null,['class'=>'form-control','placeholder'=>'Enter the abstract', 'rows'=>5]) }}
                                            @if ($errors->has('abstract'))
                                                <small class="help-block">{{ $errors->first('abstract') }}</small> @endif
                                        </div>


                                        <div class="form-group  @if ($errors->has('content')) has-error @endif">
                                            {{ Form::label('content','Text') }}
                                            {{ Form::textarea('content',null,['class'=>'form-control editorBootstrap','placeholder'=>'Enter the text here.']) }}
                                            @if ($errors->has('content'))
                                                <small class="help-block">{{ $errors->first('content') }}</small> @endif
                                        </div>


                                    </div>
                                </div>

                                <div class="tab-pane " id="category_tab">
                                    <div class="box-body">
                                        <div class="form-group">
                                            @foreach ($all_categories as $category)
                                                <div class="checkbox">
                                                    <label for="category_{{ $category['id']  }}">
                                                        <input type="checkbox" name="categories[]" id="category_{{ $category['id']  }}"
                                                               value="{{ $category['id'] }}"  >
                                                        @for ($i = 0; $i < $category['depth']; $i++) - @endfor
                                                        {{ $category['name'] }}
                                                    </label>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>


                                {{-- Photo Tabs  --}}
                                <div class="tab-pane" id="photo_tab">
                                    <div class="box-body">
                                        <div class="form-group  @if ($errors->has('photo_filename')) has-error @endif">
                                            {{ Form::label('photo_filename','Image') }}
                                            {{ Form::file('photo_filename',['class'=>'form-control']) }}
                                            <p class="help-block">The image must have the following dimensions: Min-Width 750px - Min-Height 350px  </p>
                                            @if ($errors->has('photo_filename'))
                                                <small class="help-block">{{ $errors->first('photo_filename') }}</small> @endif
                                        </div>
                                    </div>
                                </div>
                                {{-- Photo Tabs End --}}



                                <div class="tab-pane" id="seo_tab">
                                    <div class="box-body">

                                        <div class="form-group  @if ($errors->has('title_tag')) has-error @endif">
                                            {{ Form::label('title_tag','Title Tag ') }}
                                            {{ Form::text('title_tag',null,['class'=>'form-control','placeholder'=>'Enter the title tag']) }}
                                            @if ($errors->has('title_tag'))
                                                <small class="help-block">{{ $errors->first('title_tag') }}</small> @endif
                                        </div>

                                        <div class="form-group  @if ($errors->has('description_tag')) has-error @endif">
                                            {{ Form::label('description_tag','Description tag') }}
                                            {{ Form::textarea('description_tag',null,['class'=>'form-control','placeholder'=>'Enter the description tag', 'rows'=>5]) }}
                                            @if ($errors->has('description_tag'))
                                                <small class="help-block">{{ $errors->first('description_tag') }}</small> @endif
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>


                    </div>
                </div>

                <div class="col-md-4">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Publish</h3>
                        </div>

                        <div class="box-body">

                            <div class="form-group  @if ($errors->has('name')) has-error @endif">
                                {{ Form::label('status','Status') }}
                                {{ Form::select('status', ['draft' => 'Draft', 'publish' => 'Publish'], null, ['class' => 'form-control']) }}
                                @if ($errors->has('name'))
                                    <small class="help-block">{{ $errors->first('name') }}</small>
                                @endif
                            </div>




                            <div class="form-group  @if ($errors->has('publish_date')) has-error @endif">
                                {{ Form::label('publish_date','Publish date') }}
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    {{ Form::text('publish_date', \Carbon\Carbon::now()->format('d/m/Y') ,['class' => 'form-control datepicker'])}}
                                </div>
                                @if ($errors->has('publish_date'))
                                    <small class="help-block">{{ $errors->first('publish_date') }}</small>
                                @endif
                            </div>

                        </div>






                        <div class="box-footer">
                            {{ Form::submit('Save', ['class'=>'btn btn-primary']) }}
                        </div>

                    </div>
                </div>
            </div>
            </div>
            </form>


        </div>
    </section>
    @stop

resources/views/backend/posts/index.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header">
        <h1>
            Post
        </h1>
   </section>


    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('posts.create') }}" class="btn btn-success">New</a>
        </div>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">

                @include('includes.form_error')
                @include('includes.message')

                <div class="box">
                    <div class="box-header with-border">

                        <h3 class="box-title">
                            Your posts
                        </h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-striped table-bordered">
                            <tbody>
                            <tr >
                                <th class="col-md-1">#</th>
                                <th class="col-md-3">Post title</th>
                                <th class="col-md-2">Author</th>
                                <th class="col-md-2">Status</th>
                                <th class="col-md-2">Publish date</th>
                                <th class="col-md-2">Action</th>
                            </tr>
                            @foreach($posts as $post)
                            <tr id="tr-{{$post->id}}">
                                <td>{{ $post->id }}</td>
                                <td>{{ $post->title }}</td>
                                <td>{{ $post->user->name }}</td>
                                <td>{{ $post->status }}</td>
                                <td>{{ $post->publish_date }}</td>
                                <td>
                                    <a href="{{ route('posts.edit',$post->id) }}" class="btn btn-primary" title="Edit"><i class="fa fa-pencil"></i></a>
                                    <a  class="btn btn-danger confirm-delete"
                                        data-element="{{ route('posts.destroy', $post->id) }}"  data-id="{{$post->id}}" data-message="Do you want delete this item?"  title="Delete" role="button" ><i class="fa fa-trash-o"></i></a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">

                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
    @stop