routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/




// Route for Backend panel
Route::group(['prefix' => 'backend', 'middleware'=>'role:admin|author' ], function(){


    Route::get('/', function () {
        return view('backend.index');
    })->name('dashboard');

    /*
     * Backend Categories Route
     *
     */
       Route::group(['middleware'=>'role:admin' ], function(){
       Route::resource('categories','Backend\BackendCategoryController',['except' => ['index','show']]);
       Route::get('categories/{parent_id?}', 'Backend\BackendCategoryController@index')->name('categories.index');
       Route::get('categories/delete/{category_id}', 'Backend\BackendCategoryController@delete')->name('categories.delete');

       /*
        * Backend User Route
        *
        */

       Route::resource('users','Backend\BackendUserController');
       Route::get('users/delete/{user_id}', 'Backend\BackendUserController@delete')->name('users.delete');

    });


    /*
     * Backend Post Route
     *
     */
    Route::delete('posts/destroyTrashed', 'Backend\BackendPostController@destroyTrashed')->name('posts.destroyTrashed');
    Route::resource('posts','Backend\BackendPostController',['except' => ['show']]);
    Route::get('posts/trash', 'Backend\BackendPostController@trash')->name('posts.trash');
    Route::get('posts/restore/{post}', 'Backend\BackendPostController@restore')->name('posts.restore');



    /*
     * Edit Profile User : Accessible for Admin And Author
     *
     */

    Route::get('profile', 'Backend\BackendUserController@editProfile')->name('user.profile');
    Route::post('profile/{profile}', 'Backend\BackendUserController@updateProfile');



});


Auth::routes();



/*
 * Public Post
 *
 */

Route::get('/', ['uses' => 'Blog\BlogController@index', 'as' => 'blog.index']);
Route::get('/{slug}','Blog\BlogController@showPost')->name('blog.showPost');


/*
 * Public Category
 *
 */
Route::get('/category/{name}','Blog\BlogController@showPostsInCategory')->name('blog.showPostsInCategory');

app/User.php
<?php

namespace App;

use App\Post;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'last_name', 'email', 'password', 'is_active', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    /**
     * Create the 'role' relationship between User and Role models. 1 - 1
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function role(){
        return $this->belongsTo('App\Role');
    }


    /**
     * Create the 'posts' relationship between User and Post models. 1 - N
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function posts(){
        return $this->hasMany('App\Post');
    }



    /**
     * Check if the user has the role passed as parameter and it is active
     *
     *
     * @param string $role
     * @return bool
     */
    public function hasRole($role){

        // Change $role to Array. So we can have ['admin','author'])
        $A_role = explode('|',$role);

        if( is_array($A_role) ) {
            if ( in_array( $this->role->name, $A_role ) && $this->is_active == 1 ) {
                return true;
            }
        }

        return false;
    }






    /**
     * Delete the give category id  and all his sub-category and relative posts
     *
     * @param $id - The category id to delete
     * @return bool
     */
    public function deletePostAndUser($id)
    {
        $user_posts = $this->find($id)->posts()->get()->toArray();


        if(count($user_posts)>0) {
            foreach ($user_posts as $post) {


                Post::find($post['id'])->delete();

                // Delete entry in pivot
                if( !\DB::table('category_post')->where('post_id', '=', $post['id'])->delete() ){
                    return false;
                }



            }
        }


        if ($this->whereId($id)->delete()) {
            return true;
        }
        return false;
    }


    /**
     * Move post to another user
     *
     * @param $user_id
     * @param $new_user_id
     * @return bool
     *
     */
    public function movePostsToUser($user_id, $new_user_id)
    {


        if( \DB::table('posts')->where('user_id', '=', $user_id)->update(['user_id' => $new_user_id]) ){
            return true;
        }
        return false;
    }



}

app/Http/Controllers/Backend/BackendCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class BackendCategoryController extends Controller
{



    /**
     * The category repository instance.
     */
    protected $categories;

    /**
     * Assign Category Model in Controller
     *
     * @param  Category $categories
     */
    public function __construct(Category $categories)
    {
        $this->categories = $categories;
    }




    /**
     * Display a listing of all the categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($parent_id=0)
    {


        // Get the categories child of the $id
        $categories = Category::childOf($parent_id)->withCount('children')->paginate(10);

        $next_parent_id = 0;
        $parent_name = null;



        if($parent_id>0){
            $current_parent_category = Category::findOrFail($parent_id);

            // Save the next Parent Category
            $next_parent_id = $current_parent_category->parent_id;
            //Get the current name of the category parent
            $parent_name = $current_parent_category->name;
        }

       return view('backend.categories.index', compact('categories','next_parent_id','parent_name'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories_tree = $this->categories->listTreeCategories();
        if($categories_tree>0) {
            $categories = $this->categories->linearizeCategoryArray($categories_tree);
        }

        return view('backend.categories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // Set some rules, I Set here because are only few rows
        $this->validate( $request, [
            'name' => 'required|max:250',
            'parent_id' => 'required|numeric|min:0',
        ]);

        //Recovery input data
        $input_data = $request->all();

        // Create new category
        $new_category = $this->categories->create($input_data);

        if ($new_category) {
                //  Create new insert in pivot table
                $seo_data = $new_category->seo()->create($input_data);
                $new_category->seo()->save($seo_data);

            \Session::flash('flash_message_success', 'Success! Entry saved.');
        }else{
            \Session::flash('flash_message_error', 'Error! Entry Not saved.');
        }






        // Return to list Category page
        return redirect()->route('categories.index');

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categories->findOrFail($id);

        $categories_tree = $category->listTreeCategories();
        $categories = $category->linearizeCategoryArray($categories_tree);

        // retrieve seo data
        $seo = $category->seo->first();



        return view('backend.categories.edit', compact('category','categories','seo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // Set some rules, I Set here because are only few rows
        $this->validate( $request, [
            'name' => 'required|max:250',
            'parent_id' => 'required|numeric|min:0',
        ]);

        //Recovery input data
        $input_data = $request->all();

        $category = $this->categories->find($id);


        if ($category->update($input_data)) {

            $category->seo()->update(['title_tag'=>$input_data['title_tag'], 'description_tag'=>$input_data['description_tag']]);

            \Session::flash('flash_message_success', 'Success! Entry updated.');
        }else{
            \Session::flash('flash_message_error', 'Error! Entry Not updated.');
        }


        return redirect()->route('categories.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     * We retrieve the user choose about how manage sub folder and posts
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        //Recovery input data
        $input_data = $request->all();

        if(intval($input_data['delete_option'])>0){

            switch ($input_data['delete_option']){

                case 1 : $result = $this->categories->deleteCategoryAndSubcategory($id);
                         break;

                case 2 : $result = $this->categories->moveSubcategory($id,$input_data['move_in_id_category']);
                          break;

                case 3 :  $result = $this->categories->movePostsToCategory($id, $input_data['new_id_category']);

                         break;
            }

        }



        if($result){
            \Session::flash('flash_message_success', 'Success! Category deleted.');
        }else{
            \Session::flash('flash_message_error', 'Error! Category Not deleted.');
        }

        return redirect()->route('categories.index');
    }




    /**
     * Show the form with options for delete the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $category = Category::findOrFail($id);

        //Check some point
        // 1) Did The Category selected has sub-categories?
        // If it has, so I need to ask to user what they want to do with subfolder (delete, Move)
            $has_sub_category = $category->children()->count();

         //2) Did the category selected has post?
        //If it has,  so I need to ask to user what they want to do with Posts (delete, Move)
            $has_posts = $category->posts()->count();

        // Get all Category tree except the category branch and its related sub category
        $categories_tree = $this->categories->listTreeCategories(0,$id);

        // Linearize in array
        $categories_available = $this->categories->linearizeCategoryArray($categories_tree);

        return view( 'backend.categories.delete', compact('category', 'has_sub_category', 'has_posts', 'categories_available') );
    }



}

app/Http/Controllers/Backend/BackendPostController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Http\Requests\PostCreateRequest;
use App\Http\Requests\PostUpdateRequest;
use App\Post;
use App\User;
use App\Repositories\BackendPostRepository;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackendPostController extends Controller
{


    /**
     * The post repository instance.
     */
    protected $postRepository;

    /**
     * Assign Category Model in Controller
     *
     * @param  BackendPostRepository $post
     * @return void
     */
    public function __construct(BackendPostRepository $post)
    {

        $this->postRepository = $post;
    }




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Check the role of the user

        $posts = $this->postRepository->listPosts();

        return view('backend.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $all_categories = $this->postRepository->loadCategories();

        return view('backend.posts.create', compact('all_categories'));
    }

    /**
    /**
     * Save the specified resource and check validation rule in PostCreateRequest.php
     *
     * @param  App\Http\Requests\PostCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostCreateRequest $request)
    {

        $this->postRepository->save($request);

        return redirect('/backend/posts');

    }


    /**
     * Show the form for editing the specified resource.
     * The rules for access are are stored in in app/Policies/Backend/BackendPostPolicy.php
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        // Load all the data for the Post from the repository in app/Repositories/BackendPostRepository.php
        $data = $this->postRepository->load($id);

        // Check the policy for the post, that are stored in app/Policies/Backend/BackendPostPolicy.php
        /*
         *   [
            'post' => // The post Object
            'all_categories' // All the categories
            'category_post' // Id of all the categories set for the post
            'status' => // All status available for the post
             'seo' => // Seo data for the post
        ];
         */

        return view( 'backend.posts.edit', $data );
    }



    /**
     * Update the specified resource and check validation rule in PostUpdateRequest.php
     *
     * @param  App\Http\Requests\PostUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, $id)
    {
        $post = $this->postRepository->find($id);

        if ($this->postRepository->update($request, $id)) {
            \Session::flash('flash_message_success', 'Success!');
        }else{
            \Session::flash('flash_message_error', 'Error!');
        }

        return redirect()->route('posts.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     * The method can be called only via AJAX
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $post = $this->postRepository->find($id);

        $this->authorize('delete', $post);

        // check to see if the request is
        // an AJAX call.
        if ($request->ajax()) {
            $this->postRepository->delete($id);
        }
    }





    /**
     * Display a listing of the post soft-deleted.
     *
     * @return \Illuminate\Http\Response
     */
    public function trash()
    {
        $posts = $this->postRepository->listPosts(true);

        return view('backend.posts.trashed', compact('posts'));
    }


    /**
     *
     *
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {

        // Load all the data for the Post from the repository in app/Repositories/BackendPostRepository.php
        $data = $this->postRepository->loadRestore($id);

        // Check the policy for the post, that are stored in app/Policies/Backend/BackendPostPolicy.php
        /*
         *   [
            'post' => // The post Object
            'all_categories' // All the categories
            'category_post' // Id of all the categories set for the post
            'status' => // All status available for the post
        ];
         */
      return view('backend.posts.edit', $data);
    }




    /**
     * Remove the specified resource earlier trashed ( soft delete ).
     * The method can be called only via AJAX
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroyTrashed(Request $request)
    {
        // check to see if the request is
        // an AJAX call.
        if ($request->ajax()) {
          return  $this->postRepository->deleteTrashed($request['id']);
         }
    }

}

resources/views/backend/users/create.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header">
        <h1>Users</h1>
    </section>

    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('users.index') }}" class="btn btn-info"><i class="fa  fa-angle-double-left"></i> Back
            </a>
        </div>
    </section>



    <section class="content">

        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

            @include('includes.form_error')
            @include('includes.message')

            <!-- general form elements -->
                {!! Form::open(['method'=>'POST', 'action' => ['Backend\BackendUserController@store'], 'files'=>false]) !!}


                <div class="row">
                    <div class="col-md-8">
                        <div class="box box-primary">

                            <div class="box-header with-border">
                                <h3 class="box-title">Create User</h3>
                            </div>


                            <div class="box-body">

                                <div class="form-group  @if ($errors->has('name')) has-error @endif">
                                    {!! Form::label('name','Name') !!}
                                    {!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Enter name']) !!}
                                    @if ($errors->has('name'))
                                        <small class="help-block">{{ $errors->first('name') }}</small> @endif
                                </div>


                                <div class="form-group  @if ($errors->has('last_name')) has-error @endif">
                                    {!! Form::label('last_name','Last name') !!}
                                    {!! Form::text('last_name',null, ['class'=>'form-control', 'placeholder'=>'Enter last name']) !!}
                                    @if ($errors->has('last_name'))
                                        <small class="help-block">{{ $errors->first('last_name') }}</small> @endif
                                </div>


                                <fieldset class="form-group">
                                    {!! Form::label('title','email') !!}
                                    {!! Form::email('email',null,['class'=>'form-control']) !!}
                                    @if ($errors->has('email'))
                                        <small class="help-block">{{ $errors->first('email') }}</small> @endif
                                </fieldset>

                                <div class="form-group  @if ($errors->has('password')) has-error @endif">
                                    {!! Form::label('password','Password') !!}
                                    {!! Form::password('password', ['class'=>'form-control', 'placeholder'=>'Leave empty for not change']) !!}

                                    <small class="text-red"> The password must be lenght between 5 and 10 characters.</small>

                                </div>


                            </div>


                        </div>
                    </div>


                    <div class="col-md-4">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">Status and role</h3>
                            </div>


                            <div class="box-body">
                                <div class="form-group  ">
                                    <label for="status">Role</label>
                                    {{ Form::select('role_id', $roles, null, ['class'=>'form-control']) }}

                                </div>
                            </div>

                            <div class="box-body">
                                <div class="form-group  ">
                                    <label for="status">Status</label>
                                    {!! Form::select('is_active',[1=>'active',0=>'Not active'],null,['class'=>'form-control']) !!}

                                </div>
                            </div>



                            <div class="box-footer">
                                {!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
                            </div>

                        </div>
                    </div>


                </div>
        {!! Form::close() !!}
    </section>
@stop

resources/views/backend/users/delete.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header" xmlns="http://www.w3.org/1999/html">
        <h1>User</h1>
    </section>

    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('users.index') }}" class="btn btn-info"><i class="fa  fa-angle-double-left"></i> Back </a>
        </div>
    </section>



        <section class="content">

        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

            @include('includes.form_error')
            @include('includes.message')

                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Delete User <strong class="text-red">{{ $user->name }}</strong></h3>
                    </div>

                    {!! Form::open(['method'=>'DELETE', 'action' => ['Backend\BackendUserController@destroy', $user->id], 'files'=>false]) !!}
                        <div class="box-body">



                                <p class="text-red">Attention!</p>
                                <div class="form-group">

                                    <div class="radio">
                                        <label for="delete_option_1">
                                            <input type="radio" name="delete_option" id="delete_option_1" value="1" checked>
                                             Delete  <strong class="text-red">{{ $user->name }}</strong>  @if($has_posts>0) include his posts @endif
                                        </label>
                                    </div>



                            @if($has_posts>0)

                                <div class="radio">
                                    <label for="delete_option_2">
                                        <input type="radio" name="delete_option" id="delete_option_2" value="2">

                                        Move Posts to  :
                                        <select class="form-control" name="new_id_user">

                                            @foreach ($all_users as $user_item)
                                                <option value="{{ $user_item['id'] }}">
                                                    {{ $user_item['name'] }}   {{ $user_item['last_name'] }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </label>
                                </div>
                        </div>
                    @endif







                        </div>

                        <div class="box-footer">
                            {!! Form::submit('Execute', ['class'=>'btn btn-danger']) !!}
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    @stop

resources/views/backend/users/edit_profile.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header">
        <h1>Users</h1>
    </section>

    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('users.index') }}" class="btn btn-info"><i class="fa  fa-angle-double-left"></i> Back
            </a>
        </div>
    </section>



    <section class="content">

        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

            @include('includes.form_error')
            @include('includes.message')

            <!-- general form elements -->
                {!! Form::model($user, ['method'=>'POST', 'action' => ['Backend\BackendUserController@updateProfile', $user->id], 'files'=>false]) !!}


                <div class="row">
                    <div class="col-md-8">
                        <div class="box box-primary">

                            <div class="box-header with-border">
                                <h3 class="box-title">Edit User</h3>
                            </div>


                            <div class="box-body">

                                <div class="form-group  @if ($errors->has('name')) has-error @endif">
                                    {!! Form::label('name','Name') !!}
                                    {!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Enter name']) !!}
                                    @if ($errors->has('name'))
                                        <small class="help-block">{{ $errors->first('name') }}</small> @endif
                                </div>


                                <div class="form-group  @if ($errors->has('last_name')) has-error @endif">
                                    {!! Form::label('last_name','Last name') !!}
                                    {!! Form::text('last_name',null, ['class'=>'form-control', 'placeholder'=>'Enter last name']) !!}
                                    @if ($errors->has('last_name'))
                                        <small class="help-block">{{ $errors->first('last_name') }}</small> @endif
                                </div>


                                <fieldset class="form-group">
                                    {!! Form::label('title','email') !!}
                                    {!! Form::email('email',null,['class'=>'form-control']) !!}
                                    @if ($errors->has('email'))
                                        <small class="help-block">{{ $errors->first('email') }}</small> @endif
                                </fieldset>

                                <div class="form-group  @if ($errors->has('password')) has-error @endif">
                                    {!! Form::label('password','Password') !!}
                                    {!! Form::password('password', ['class'=>'form-control', 'placeholder'=>'Leave empty for not change']) !!}
                                    <small class="text-red"> The password must be lenght between 5 and 10 characters.</small>
                                </div>





                            </div>

                            <div class="box-footer">
                                {!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
                            </div>


                        </div>
                    </div>






                </div>
        {!! Form::close() !!}
    </section>
@stop

resources/views/backend/users/index.blade.php
@extends('layouts.backend')

@section('content')

    <section class="content-header">
        <h1>
            Users
        </h1>
   </section>


    <section class="content-header">
        <div class="row-fluid">
            <a href="{{ route('users.create') }}" class="btn btn-success">New</a>
        </div>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">

                @include('includes.form_error')
                @include('includes.message')

                <div class="box">
                    <div class="box-header with-border">

                        <h3 class="box-title">
                            Manage users
                        </h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-striped table-bordered">
                            <tbody>
                            <tr>
                                <th class="col-md-1">#</th>
                                <th class="col-md-3">Name</th>
                                <th class="col-md-3">Last name</th>
                                <th class="col-md-1">Role</th>
                                <th class="col-md-2">Active</th>
                                <th class="col-md-2">Action</th>
                            </tr>
                            @foreach($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->last_name }}</td>
                                <td>{{ $user->role->name }}</td>
                                <td>{{$user->is_active ? 'Active' : 'Not Active' }}</td>
                                <td>
                                    <a href="{{ route('users.edit',$user->id) }}" class="btn btn-primary" title="Edit category"><i class="fa fa-pencil"></i></a>

                                    <a href="{{ route('users.delete',$user->id) }}" class="btn btn-danger" title="Delete items" ><i class="fa fa-trash-o"></i></a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">

                    </div>
                </div>
                <!-- /.box -->

            </div>
        </div>
    </section>
    @stop